> ###  **Self Practice Assignment 2 - Numpy Array Operations** 


# NumPy Operations:


### A set of useful fuctions on the NumPy documentation page implemented:

Write a short introduction about Numpy and list the chosen functions. 

- np.hstack: Stack arrays in sequence horizontally (column wise).
- np.reshape : Gives a new shape to an array without changing its data.
- np.flip : Reverse the order of elements in an array along the given axis. The shape of the array is preserved, but the elements are reordered.
- np.ravel : Return a contiguous flattened array.
- np.full : Return a new array of given shape and type, filled with fill_value.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np
import numpy.matlib

In [7]:
# List of functions explained 
function1 = np.hstack
function2 = ???
function3 = ???
function4 = ???
function5 = ???

SyntaxError: invalid syntax (3200869023.py, line 3)

## Function 1 - np.hstack

Add some explanation about the function in your own words

In [11]:
# Example 1 - working:
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.hstack((arr1, arr2))

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example in 3d array:

In [16]:
# Example 2 - working

a = np.array(('a','b','c'))
b = np.array(('d','e','f'))
np.hstack((a,b))

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

As you can see above the two set of lists are stacked horizontally

In [17]:
# Example 3 - breaking 
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.hstack((arr1, arr2))

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

This is similar to the numpy concatenate function, except for this case here arrays are stacked column wise as shown in the example above. Notice that we cannot use the axis definition.

This functions makes most sense to use in a 3D array

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

## Function 2 - np.reshape

Gives a new shape to an array without changing its data.

In [36]:
# Example 1 - working
a= np.array([[1, 2], 
             [3, 4.], 
             [2,6]])

a.shape

np.reshape(a,(2,3))

array([[1., 2., 3.],
       [4., 2., 6.]])

You can think of reshaping as first raveling the array (using the given index order), then inserting the elements from the raveled array into the new array using the same kind of index ordering as was used for the raveling.

In [38]:
# Example 2 - working
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

Lets reshape the above array b:

In [43]:
np.reshape(b,(3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.array([[1,2,3], [4,5,6]])
np.reshape(c,6,order='F'  )

array([1, 4, 2, 5, 3, 6])

order{‘C’, ‘F’, ‘A’} are optional.
 ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

## Function 3 - np.flip

Reverse the order of elements in an array along the given axis. The shape of the array is preserved, but the elements are reordered.

In [55]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

np.flip(arr1,axis=1)

array([[2., 1.],
       [4., 3.]])

Explanation about example

In [58]:
# Example 2 - working
arr2 = [[5, 6, 7, 8], 
        [9, 10, 11, 12]]

np.flip(arr2,axis=1)

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9]])

As you can see above how the functip flips the list of values

In [64]:
# Example 3 - breaking (to illustrate when it breaks)
A = np.arange(8).reshape((2,2,2))
A


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
A.shape

(2, 2, 2)

Lets flip this array:

In [66]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [67]:
A.shape

(2, 2, 2)

In [68]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

## Function 4 - ravel

Perhaps the most commonly used one by me.A 1-D array, containing the elements of the input, is returned. A copy is made only if needed. Returns a flat array

In [69]:
# Example 1 - working
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

The two rows of the array are flattened.

In [76]:
# Example 2 - working
a = np.arange(12)[::-1].reshape(2,3,2)
a

array([[[11, 10],
        [ 9,  8],
        [ 7,  6]],

       [[ 5,  4],
        [ 3,  2],
        [ 1,  0]]])

Lets unravel the above array:

In [79]:
np.ravel(a)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [80]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

lets unravel this one as:

In [81]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

As you can see how easily we can unrale the array

In [82]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

## Function 5 - full

Return a new array of given shape and type, filled with fill_value.

In [86]:
# Example 1 - working
np.full((2, 2), np.sin(20))

array([[0.91294525, 0.91294525],
       [0.91294525, 0.91294525]])

Returns an array of 2x2 matrix filled with sin 20 values

In [87]:
# Example 2 - working
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

Similarly, just an array of 2x2 filled with 10

In [94]:
# Example 3 - breaking (to illustrate when it breaks)
np.full((4, 4,2), [1, 2])

array([[[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]]])

Returns the array with the specified elements to create a 3d array faster

Helps for faster implementation of code with less lines

In [95]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'

## Conclusion

Summarize what I have covered in this notebook:

np.hstack
np.reshape
np.flip
np.ravel
np.full

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [98]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ranton95/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ranton95/numpy-array-operations


'https://jovian.ai/ranton95/numpy-array-operations'